name: Upgrade version

on:
  push:
    branches:
      - master

jobs:
  upgradeVersion:
    name: "Upgrade version"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: "Run upgrade command"
        run: "node ./scripts/upgrade-version.js patch"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: "Get last tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"

      - name: "Dispatch event"
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository: ${{ github.repository }}
          event-type: upgraded
          client-payload: '{"tag": "${{ steps.previoustag.outputs.tag }}"}'
